/** Fragmento del PDF oficial Stripes (narrativa + calendario resumen al final). */
export const ARGENTINA_OFFICIAL_PDF_SNIPPET = [
  "PROGRAMA OFICIAL TRIP TO ARGENTINA 2026",
  "del 27 de Noviembre al 8 de Diciembre 2026",
  "DÍA 27 de Noviembre. Viernes",
  "16.00h- Quedada Grupal en el Aeropuerto Barajas T1",
  "19.05h- Vuelo MADRID-BUENOS AIRES",
  "DÍA 28 de Noviembre. Sábado",
  "04.15h- WELCOME TO BUENOS AIRES",
  "07.30h- DÍA LIBRE",
  "PROGRAMA TRIP TO ARGENTINA 2026",
  "VIERNES 27",
  "- 16.00h QUEDADA GRUPAL en T1 BARAJAS para Facturar",
  "- 19.05h Vuelo MADRID-BUENOS AIRES (Aerolíneas Argentinas)",
  "SÁBADO 28",
  "- 04.15h Aterrizaje en BUENOS AIRES",
  "- 06.30h Llegada y EARLY CHECK en HOTEL NH FLORIDA",
  "- 07.30h Desayuno en Hotel",
  "- 08.30h Día Libre",
  "- 20.00h POSIBLE PARTIDO TORNEO CLAUSURA FÚTBOL",
  "DOMNGO 29",
  "- 07.30h Desayuno en Hotel",
  "- 08.30h EXCURSIÓN GUIADA BUENOS AIRES SUR",
  "- 17.30h Tarde libre",
  "- 20.00h POSIBLE PARTIDO TORNEO CLAUSURA FÚTBOL",
  "LUNES 30",
  "- 07.30h Desayuno en Hotel",
  "- 08.30h EXCURSIÓN GUIADA BUENOS AIRES NORTE",
  "- 17.30h Tarde libre",
  "- 20.00h POSIBLE PARTIDO TORNEO CLAUSURA FÚTBOL",
  "MARTES 1",
  "- 06.00h Desayuno en hotel",
  "- 07.00h QUEDADA HALL HOTEL PARA BUS A AIRPORT",
  "- 08.30h CHECK IN AIRPORT",
  "- 11.00h Vuelo BUENOS AIRES-USHUAIA",
  "- 14.40h LLEGADA A USHUAIA",
  "- 15.35h LLEGADA A HOTEL CILENE DEL FARO SUITES & SPA",
  "- 16.00h TARDE LIBRE.",
  "MIÉRCOLES 2",
  "- 07.30h Desayuno en hotel",
  "- 09.15h EXCURSIÓN PARQUE NACIONAL TIERRA DEL FUEGO",
  "- 17.30h Tarde – Noche libre",
  "JUEVES 3",
  "- 07.00h Desayuno en hotel",
  "- 08.00h QUEDADA HALL HOTEL PARA BUS A AIRPORT",
  "- 08.30h CHECK IN AIRPORT",
  "- 11.20h Vuelo USHUAIA – EL CALAFATE",
  "- 12.40h LLEGADA A EL CALAFATE",
  "- 13.45h LLEGADA A HOTEL IMAGO & SPA",
  "- 14.00h TARDE LIBRE.",
  "VIERNES 4",
  "- 07.30h Desayuno en hotel",
  "- 09.15h EXCURSIÓN GLACIAR PERITO MORENO",
  "- 17.30h Tarde – Noche libre",
  "SÁBADO 5",
  "- 07.00h Desayuno en hotel",
  "- 08.00h MAÑANA LIBRE",
  "- 11.30h QUEDADA HALL HOTEL PARA BUS A AIRPORT",
  "- 12.30h CHECK IN AIRPORT",
  "- 14.30h Vuelo EL CALAFATE – BUENOS AIRES – IGUAZÚ",
  "- 20.35h LLEGADA A IGUAZÚ",
  "- 21.45h LLEGADA A FALLS IGUAZÚ HOTEL & SPA",
  "- 22.00h NOCHE LIBRE.",
  "DOMINGO 6",
  "- 08.00h Desayuno en hotel",
  "- 09.15h EXCURSIÓN CATARATAS IGUAZÚ ZONA ARGENTINA",
  "- 14.30h Tarde – Noche libre",
  "LUNES 7",
  "- 08.00h Desayuno en hotel",
  "- 11.30h EXCURSIÓN CATARATAS IGUAZÚ ZONA BRASILEÑA",
  "- 16.00h QUEDADA PARA BUS AL AIRPORT",
  "- 16.30h LLEGADA A AIRPORT Y FACTURACIÓN",
  "- 18.55h Vuelo IGUAZÚ-BUENOS AIRES-MADRID",
  "MARTES 8",
  "- 16.15h LLEGADA a T1, RECOGER MALETAS, FIN TRIP",
  "Precios",
  "De 15 a 19 personas: 3995 euros",
].join("\n");
